'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by SpecFlow (http://www.specflow.org/).
'     SpecFlow Version:1.8.1.0
'     Runtime Version:2.0.50727.3625
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
#Region "Designer generated code"
Imports TechTalk.SpecFlow

Namespace SkeletonCodeerFriendly.Features
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0"),  _
     System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     NUnit.Framework.TestFixtureAttribute(),  _
     NUnit.Framework.DescriptionAttribute("Form1の動作テスト")>  _
    Partial Public Class Form1の動作テストFeature
        
        Private Shared testRunner As TechTalk.SpecFlow.ITestRunner
        
#ExternalSource("FeatureForm1.feature",1)
#End ExternalSource
        
        <NUnit.Framework.TestFixtureSetUpAttribute()>  _
        Public Overridable Sub FeatureSetup()
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner
            Dim featureInfo As TechTalk.SpecFlow.FeatureInfo = New TechTalk.SpecFlow.FeatureInfo(New System.Globalization.CultureInfo("en-US"), "Form1の動作テスト", "", ProgrammingLanguage.VB, CType(Nothing,String()))
            testRunner.OnFeatureStart(featureInfo)
        End Sub
        
        <NUnit.Framework.TestFixtureTearDownAttribute()>  _
        Public Overridable Sub FeatureTearDown()
            testRunner.OnFeatureEnd
            testRunner = Nothing
        End Sub
        
        <NUnit.Framework.SetUpAttribute()>  _
        Public Overridable Sub TestInitialize()
        End Sub
        
        <NUnit.Framework.TearDownAttribute()>  _
        Public Overridable Sub ScenarioTearDown()
            testRunner.OnScenarioEnd
        End Sub
        
        Public Overridable Sub ScenarioSetup(ByVal scenarioInfo As TechTalk.SpecFlow.ScenarioInfo)
            testRunner.OnScenarioStart(scenarioInfo)
        End Sub
        
        Public Overridable Sub ScenarioCleanup()
            testRunner.CollectScenarioErrors
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("足し算")>  _
        Public Overridable Sub 足し算()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("足し算", CType(Nothing,String()))
#ExternalSource("FeatureForm1.feature",3)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("FeatureForm1.feature",4)
 testRunner.Given("起動する")
#End ExternalSource
#ExternalSource("FeatureForm1.feature",5)
 testRunner.When("TextBox ""TextBox1"" に ""12"" を入力する")
#End ExternalSource
#ExternalSource("FeatureForm1.feature",6)
  testRunner.And("TextBox ""TextBox2"" に ""34"" を入力する")
#End ExternalSource
#ExternalSource("FeatureForm1.feature",7)
  testRunner.And("Button ""+"" を押す")
#End ExternalSource
#ExternalSource("FeatureForm1.feature",8)
 testRunner.Then("TextBox ""TextBox3"" は ""46"" になる")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
    End Class
End Namespace
#End Region
